os:
  - Visual Studio 2019
  
environment:
  VCPKG_VISUAL_STUDIO_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community"
  VCPKG_PLATFORM_TOOLSET: v142

configuration:
  - Release

platform:
  - Win32
  
install:
  - cmd: rmdir /s C:\MinGW
  - vcpkg install freetype
  
before_build:
  - cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: fontbm.sln
  
after_build:
 - 7z a fontbm.zip "./Release/*" "-x!unit_tests.exe"

artifacts:
  - path: fontbm.zip
    name: fontbm

deploy:
  provider: GitHub
  description: 'fontbm windows binaries'
  auth_token:
    secure: IuMkEFtoGHDsFlHDQDv7oPJDC+THkDbyV4QFXxRPqeKpfH+UbZ8pJN4zN9Txx/kC
  artifact: fontbm
  on:
    appveyor_repo_tag: true
