name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: list current directory
      run: ls

    - name: cmake
      run: cmake -DCMAKE_CXX_FLAGS=-Werror .
