name: macOS build

on: [push]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: cmake -DCMAKE_CXX_FLAGS=-Werror .

    - name: make
      run: make
